sudo: required
services:
  - docker

before_install:
  - docker build -t amilinko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amilinko/react-test npm test

after_success:
  - docker build -t amilinko/client ./client
  - docker build -t amilinko/nginx ./nginx
  - docker build -t amilinko/server ./server
  - docker build -t amilinko/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push amilinko/client
  - docker push amilinko/nginx
  - docker push amilinko/server
  - docker push amilinko/worker