version: 2
jobs:
  test:
    machine: true
    steps:
      - run: docker build -t amilinko/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true amilinko/react-test npm test
  build:
    machine: true
    steps:
      - run: docker build -t amilinko/client ./client
      - run: docker build -t amilinko/nginx ./nginx
      - run: docker build -t amilinko/server ./server
      - run: docker build -t amilinko/worker ./worker
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_ID --password-stdin
      - run: docker push amilinko/client
      - run: docker push amilinko/nginx
      - run: docker push amilinko/server
      - run: docker push amilinko/worker
workflows:
  version: 2
  test_build:
    jobs:
      - build
      - test
